In [1]:
import pandas as pd

In [2]:
gov_2020_path = '../data/budgetprop-2020.xlsx'

df = pd.read_excel(gov_2020_path, engine='openpyxl', sheet_name='Utgifter fixad', skiprows=1, dtype=str)

In [3]:
df

    Nivå 1 Nivå 2 Nivå 3                                     Namn      Kronor
0        1    NaN    NaN                          Rikets styrelse    15907564
1        1      1    NaN                            1 Statschefen      147838
2        1      1      1         1 Kungliga hov- och slottsstaten      147838
3        1      2    NaN    2 Riksdagen samt Riksdagens ombudsmän     2461372
4        1      2      1  1 Riksdagens ledamöter och partier m.m.      976869
..     ...    ...    ...                                      ...         ...
575     26      1      2                   2 Oförutsedda utgifter       10000
576     26      1      3  3 Riksgäldskontorets provisionsutgifter      145200
577     27    NaN    NaN         Avgiften till Europeiska unionen    45037439
578     27      1      1       1 Avgiften till Europeiska unionen    45037439
579    NaN    NaN    NaN                             Summa anslag  1165822520

[580 rows x 5 columns]